### ISSUE TITLE
Bower package + possible merge?

### ISSUE THREAD

**Issue by markcellus** [cyberua/modalJS#1]
Hello,

I've noticed you dont have any published bower versions of your package. Are you still using the bower package name? If not, I was wondering if I could adopt it? 

In noticing that, I've also realized that we have very very similar intentions behind our modal classes! Would you be open to merging them together in a repo?

My package is located here:
https://github.com/mkay581/modal-js

Let me know your thoughts

**Comment by arshtepe** [comment]
Hello,i have been writing new version 2.0 of this script and i will want to create new repository for it with name "multiPopupJS", and so i agree to open  merging  together for this repo.

**Comment by markcellus** [comment]
Okay first you'll need to unregister this as a package on bower, so we can point to my version. You do that by following the directions on [this page](http://bower.io/docs/creating-packages/#unregister) which means basically running the following command in your terminal:

```
bower unregister modal-js
```

Once you've done that, let me know so I can point it to my repository. Then we can discuss next steps.
